### ISSUE TITLE
Twitter Thread | free resources for learning React

### ISSUE THREAD

**Issue by rutikwankhade** [tanaypratap/reactnews.dev#1]
Hey Tanay, I just found this **twitter thread** with full of **_free resources for learning react_**. 
It contains links to free courses, bootcamps and youtube videos.
I think this will be great for reactnews.dev newsletter.
Here is a link to the thread.
https://twitter.com/chrisachard/status/1179806305680265217

**Comment by tanaypratap** [comment]
This is great. Thanks for sharing.

./Tanay
I teach coding for free online. If you or someone you know is looking out
to learn join 30K students across 50 countries to learn web development
with me on learncodingfree.org
